import test from 'node:test';
import assert from 'node:assert/strict';
import {act,createRoom,joinRoom,legal,newDeck,settle,tick,view} from '../lib/engine';
import {compare,evaluate} from '../lib/evaluator';
import type {Room,Settings} from '../lib/types';
const settings:Settings={theme:'classic',maxPlayers:10,startingStack:1000,smallBlind:10,bigBlind:20,turnSeconds:30};
function table(n=3){const r=createRoom('ABC234','Test table','Player 0','token0',settings,1000);for(let i=1;i<n;i++)joinRoom(r,`Player ${i}`,`token${i}`,1000);return r;}
function start(r:Room){act(r,r.players.find(p=>p.id===r.hostId)!.tokenHash,{type:'start'},1000);}
function move(r:Room,kind:'call'|'check'|'fold'|'raise',amount?:number){const p=r.players.find(p=>p.id===r.turnId)!;act(r,p.tokenHash,{type:'act',move:kind,amount,expectedAction:r.actionNo},1100);}
function passive(r:Room){let steps=0;while(r.phase!=='showdown'&&steps++<200){move(r,r.currentBet>r.players.find(p=>p.id===r.turnId)!.bet?'call':'check');}assert.equal(r.phase,'showdown');}
function approve(r:Room,kind:'bomb'|'bounty'|'sevenDeuce'|'ocean',amount=0){act(r,'token0',{type:'propose',kind,amount},1000);const id=r.vote!.id;for(const p of r.players.slice(1))act(r,p.tokenHash,{type:'vote',voteId:id,yes:true},1000);}
const total=(r:Room)=>r.players.reduce((s,p)=>s+p.stack+(r.phase==='showdown'||r.phase==='waiting'?0:p.contributed),0)+(r.bounty?.reserve?r.bounty.reserve*r.bounty.players.length:0)+(r.sevenDeuce?Object.values(r.sevenDeuce.reserves).reduce((s,n)=>s+n,0):0);
test('52 unique cards, unbiased Fisher–Yates shuffle input',()=>{for(let i=0;i<20;i++){const deck=newDeck();assert.equal(deck.length,52);assert.equal(new Set(deck).size,52);}});
test('hand evaluation orders all categories and recognizes the wheel',()=>{
 const hands=[['As','Jh','9c','7d','3h'],['As','Ah','9c','7d','3h'],['As','Ah','9c','9d','3h'],['As','Ah','Ac','7d','3h'],['As','2h','3c','4d','5h'],['As','Js','9s','7s','3s'],['As','Ah','Ac','7d','7h'],['As','Ah','Ac','Ad','3h'],['9s','Ts','Js','Qs','Ks']];
 for(let i=1;i<hands.length;i++)assert.ok(compare(evaluate(hands[i]).rank,evaluate(hands[i-1]).rank)>0);
 assert.deepEqual(evaluate(hands[4]).rank,[4,5]);assert.equal(evaluate(['As','Ks','Qs','Js','Ts','2d','2c']).name,'Royal flush');
 assert.throws(()=>evaluate(['As','As','Qs','Js','Ts']));
});
test('seven-card evaluation picks the higher full house and kickers',()=>{assert.deepEqual(evaluate(['As','Ah','Ad','Ks','Kh','Kd','2c']).rank,[6,14,13]);assert.ok(compare(evaluate(['As','Ah','Kd','Qd','9c','5d','3s']).rank,evaluate(['Ac','Ad','Ks','Jh','9d','5h','3c']).rank)>0);});
test('eight-card Ocean evaluation still chooses the best five cards',()=>{const hand=evaluate(['As','Ks','Qs','Js','Ts','2d','3c','4h']);assert.equal(hand.name,'Royal flush');assert.deepEqual(hand.rank,[8,14]);});
test('heads-up: dealer posts small blind and acts first preflop, last postflop',()=>{const r=table(2);start(r);assert.equal(r.dealerSeat,0);assert.equal(r.players[0].bet,10);assert.equal(r.players[1].bet,20);assert.equal(r.turnId,r.players[0].id);move(r,'call');assert.equal(r.turnId,r.players[1].id);move(r,'check');assert.equal(r.phase,'flop');assert.equal(r.turnId,r.players[1].id);passive(r);assert.equal(total(r),2000);start(r);assert.equal(r.dealerSeat,1);assert.equal(r.turnId,r.players[1].id);});
test('big blind retains its option after all preflop calls',()=>{const r=table();start(r);move(r,'call');move(r,'call');assert.equal(r.phase,'preflop');assert.equal(r.turnId,r.players[2].id);assert.ok(legal(r,r.players[2]).canRaise);move(r,'check');assert.equal(r.phase,'flop');assert.equal(r.board.length,3);});
test('a short all-in does not reopen a previous caller’s raise',()=>{const r=table();r.players[1].stack=25;start(r);move(r,'call');move(r,'raise',25);assert.equal(r.currentBet,25);move(r,'call');assert.equal(r.turnId,r.players[0].id);assert.equal(legal(r,r.players[0]).canRaise,false);assert.throws(()=>move(r,'raise',100));move(r,'call');assert.equal(r.phase,'flop');passive(r);assert.equal(total(r),2025);});
test('cumulative short raises reopen action when they reach a full raise',()=>{const r=table(4);r.players[1].stack=45;r.players[2].stack=60;start(r);move(r,'raise',40);move(r,'call');move(r,'raise',45);move(r,'raise',60);assert.equal(r.turnId,r.players[3].id);assert.equal(legal(r,r.players[3]).canRaise,true);passive(r);assert.equal(total(r),2105);});
test('illegal actions, stale action counters and unauthorized players are rejected',()=>{const r=table();start(r);assert.throws(()=>move(r,'check'));assert.throws(()=>move(r,'raise',21));assert.throws(()=>act(r,'token1',{type:'act',move:'fold',expectedAction:r.actionNo}));assert.throws(()=>act(r,'unknown',{type:'theme',theme:'dark'}));assert.throws(()=>act(r,'token1',{type:'theme',theme:'dark'}));assert.throws(()=>act(r,'token0',{type:'act',move:'call',expectedAction:r.actionNo-1}));});
function showdownFixture(){const r=table();r.phase='river';r.board=['2c','3d','7h','8s','9c'];r.players.forEach((p,i)=>{p.inHand=true;p.hole=[['As','Ad'],['Ks','Kd'],['Qs','Qd']][i];p.contributed=(i+1)*100;p.stack=0;});return r;}
test('unequal all-ins build independent side pots and refund uncalled excess',()=>{const r=showdownFixture();settle(r);assert.deepEqual(r.players.map(p=>p.stack),[300,200,100]);assert.equal(r.result!.payouts.length,2);assert.equal(total(r),600);});
test('folded contributions stay in the pot without winning any tier',()=>{const r=showdownFixture();r.players[0].folded=true;settle(r);assert.deepEqual(r.players.map(p=>p.stack),[0,500,100]);});
test('tied pots split with odd chip clockwise from dealer',()=>{const r=showdownFixture();r.board=['As','Ks','Qs','Js','Ts'];r.players.forEach((p,i)=>{p.hole=[['2h','3h'],['4h','5h'],['6h','7h']][i];p.contributed=1;});r.players[2].folded=true;r.dealerSeat=0;settle(r);assert.deepEqual(r.players.map(p=>p.stack),[1,2,0]);});
test('a fold win never reveals the opponent’s hole cards or the remaining deck',()=>{const r=table(2);start(r);let v=view(r,'token0');assert.deepEqual(v.players[1].hole,['?','?']);assert.ok(!('deck'in v));assert.ok(!('tokenHash'in v.players[1]));move(r,'fold');v=view(r,'token0');assert.deepEqual(v.players[1].hole,['?','?']);assert.equal(total(r),2000);});
test('showdown reveals only live players’ cards',()=>{const r=table();start(r);move(r,'fold');passive(r);const v=view(r,'token1');assert.deepEqual(v.players[0].hole,['?','?']);assert.notDeepEqual(v.players[2].hole,['?','?']);});
test('a player can choose to show folded cards after the hand',()=>{const r=table();start(r);move(r,'fold');passive(r);assert.deepEqual(view(r,'token1').players[0].hole,['?','?']);act(r,'token0',{type:'show'});assert.deepEqual(view(r,'token1').players[0].hole,r.players[0].hole);assert.ok(r.logs.at(-1)?.text.includes('shows'));});
test('ten players receive distinct cards and complete a hand',()=>{const r=table(10);start(r);assert.equal(new Set(r.players.flatMap(p=>p.hole)).size,20);passive(r);assert.equal(new Set([...r.players.flatMap(p=>p.hole),...r.board]).size,25);assert.equal(total(r),10000);});
test('bomb pot requires unanimity, equal antes and opens the flop without blinds',()=>{const r=table();act(r,'token0',{type:'propose',kind:'bomb',amount:50},1000);assert.throws(()=>start(r));const id=r.vote!.id;act(r,'token1',{type:'vote',voteId:id,yes:true});assert.equal(r.bombNext,null);act(r,'token2',{type:'vote',voteId:id,yes:true});start(r);assert.equal(r.phase,'flop');assert.equal(r.board.length,3);assert.deepEqual(r.players.map(p=>p.contributed),[50,50,50]);assert.deepEqual(r.players.map(p=>p.bet),[0,0,0]);assert.equal(r.turnId,r.players[1].id);passive(r);assert.equal(total(r),3000);});
test('Ocean adds a sixth community card and a final betting round',()=>{const r=table();approve(r,'ocean');assert.ok(r.oceanNext);start(r);assert.equal(r.isOcean,true);passive(r);assert.equal(r.board.length,6);assert.equal(r.result!.board.length,6);assert.equal(new Set([...r.players.flatMap(p=>p.hole),...r.board]).size,12);assert.equal(total(r),3000);});
test('declined and expired votes never enable a mode',()=>{const r=table();act(r,'token0',{type:'propose',kind:'bomb',amount:50},1000);act(r,'token1',{type:'vote',voteId:r.vote!.id,yes:false},1000);assert.equal(r.vote,null);assert.equal(r.bombNext,null);act(r,'token0',{type:'propose',kind:'bomb',amount:50},1000);tick(r,122000);assert.equal(r.vote,null);assert.equal(r.bombNext,null);});
function fixedWin(r:Room,winner:number){r.phase='river';r.board=['2c','3d','7h','8s','9c'];r.players.forEach((p,i)=>{p.inHand=true;p.folded=false;p.hole=i===winner?['As','Ad']:i===(winner+1)%3?['Ks','Kd']:['Qs','Qd'];p.stack-=10;p.contributed=10;});settle(r);}
test('last player without a main-pot win pays every opponent only when the bounty ends',()=>{const r=table();approve(r,'bounty',50);assert.deepEqual(r.players.map(p=>p.stack),[1000,1000,1000]);assert.equal(total(r),3000);fixedWin(r,0);assert.equal(r.bounty!.won.length,1);fixedWin(r,1);assert.equal(r.bounty,null);assert.deepEqual(r.players.map(p=>p.stack),[1060,1060,880]);assert.equal(total(r),3000);});
test('bounty requires present coverage but reserves nothing and cancellation changes no stacks',()=>{const r=table();assert.throws(()=>approve(r,'bounty',501));approve(r,'bounty',50);assert.deepEqual(r.players.map(p=>p.stack),[1000,1000,1000]);assert.throws(()=>joinRoom(r,'Late','late'));assert.throws(()=>act(r,'token1',{type:'leave'}));act(r,'token0',{type:'cancelBounty'});assert.deepEqual(r.players.map(p=>p.stack),[1000,1000,1000]);});
test('an active bounty from the escrow version is migrated without losing chips',()=>{const r=table();r.players.forEach(p=>p.stack-=100);r.bounty={amount:50,players:r.players.map(p=>p.id),won:[],reserve:100};assert.equal(tick(r,1000),true);assert.deepEqual(r.players.map(p=>p.stack),[1000,1000,1000]);assert.equal(r.bounty?.reserve,undefined);assert.equal(total(r),3000);});
function sevenDeuceWin(bluff=false){const r=table();approve(r,'sevenDeuce',50);r.phase='river';r.board=['7c','7d','2c','3d','4h'];r.players.forEach((p,i)=>{p.inHand=true;p.folded=bluff&&i>0;p.hole=i===0?['7s','2h']:i===1?['As','Kd']:['Qs','Jd'];p.stack-=10;p.contributed=10;});settle(r);return r;}
test('7-2 pays every opponent at showdown, reveals the hand, and refills reserves',()=>{const r=sevenDeuceWin();const winner=r.players[0];assert.deepEqual(r.players.map(p=>p.stack),[1020,840,840]);assert.deepEqual(Object.values(r.sevenDeuce!.reserves),[100,100,100]);assert.ok(r.result!.revealed.includes(winner.id));assert.deepEqual(view(r,'token1').players[0].hole,['7s','2h']);assert.equal(total(r),3000);});
test('7-2 also pays and reveals after a successful bluff',()=>{const r=sevenDeuceWin(true);assert.ok(r.result!.revealed.includes(r.players[0].id));assert.deepEqual(view(r,'token2').players[0].hole,['7s','2h']);assert.equal(total(r),3000);});
test('host cancellation returns all remaining 7-2 reserves',()=>{const r=table();approve(r,'sevenDeuce',50);assert.deepEqual(r.players.map(p=>p.stack),[900,900,900]);assert.throws(()=>joinRoom(r,'Late','late'));act(r,'token0',{type:'cancelBounty'});assert.equal(r.sevenDeuce,null);assert.deepEqual(r.players.map(p=>p.stack),[1000,1000,1000]);});
test('timeouts auto-fold an outstanding bet and auto-check a free action',()=>{const r=table(2);start(r);tick(r,31001);assert.equal(r.phase,'showdown');assert.ok(r.players[0].folded);const r2=table(2);start(r2);move(r2,'call');tick(r2,31101);assert.equal(r2.phase,'flop');assert.equal(total(r2),2000);});
test('no-timer rooms create no deadline and never auto-act',()=>{const r=table(2);r.settings.turnSeconds=0;start(r);const turnId=r.turnId;assert.equal(r.deadline,null);assert.equal(tick(r,Number.MAX_SAFE_INTEGER),false);assert.equal(r.turnId,turnId);assert.equal(r.phase,'preflop');});
test('host can resize the table between hands without dropping players',()=>{const r=table();r.players[2].seat=8;r.dealerSeat=8;act(r,'token0',{type:'seats',maxPlayers:4});assert.equal(r.settings.maxPlayers,4);assert.deepEqual(r.players.map(p=>p.seat).sort((a,b)=>a-b),[0,1,2]);assert.equal(r.dealerSeat,r.players[2].seat);assert.throws(()=>act(r,'token0',{type:'seats',maxPlayers:2}));assert.throws(()=>act(r,'token1',{type:'seats',maxPlayers:5}));start(r);assert.throws(()=>act(r,'token0',{type:'seats',maxPlayers:6}));});
test('late join waits until next hand and reconnect reclaims the same seat',()=>{const r=table(2);start(r);joinRoom(r,'Third','third');assert.equal(r.players[2].inHand,false);joinRoom(r,'Third','third');assert.equal(r.players.length,3);passive(r);start(r);assert.equal(r.players[2].hole.length,2);});
test('absent host transfers to a recently connected player',()=>{const r=table();r.players[1].lastSeen=100000;tick(r,100000);assert.equal(r.hostId,r.players[1].id);});
test('random legal actions conserve chips and finish 500 hands, including all-ins',()=>{
 let seed=90731;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 for(let game=0;game<500;game++){
  const n=2+Math.floor(random()*9);const r=table(n);r.players.forEach(p=>p.stack=20+Math.floor(random()*1000));const before=total(r);start(r);let steps=0;
  while(r.phase!=='showdown'&&steps++<500){const p=r.players.find(p=>p.id===r.turnId)!;const l=legal(r,p);const rand=random();if(rand<.15)move(r,'fold');else if(rand<.4&&l.canRaise){const amount=rand<.22?l.maxRaiseTo:Math.min(l.maxRaiseTo,l.minRaiseTo+Math.floor(random()*Math.max(0,l.maxRaiseTo-l.minRaiseTo)));move(r,'raise',amount);}else move(r,l.call?'call':'check');assert.equal(total(r),before);assert.ok(r.players.every(p=>p.stack>=0&&Number.isSafeInteger(p.stack)));}
  assert.equal(r.phase,'showdown');assert.equal(total(r),before);
 }
});
